spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/b-push-center?Unicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false
    username: yygsmctest
    password: HBT!hyyx2023test
    driver-class-name: com.mysql.jdbc.Driver


exportFileName:
  transactionClearingSummary: 预付卡交易清算汇总报表